// src/components/blocks/HistoryList.vue
<script lang="ts" setup>
import { IStorageHistoryItem } from '@/utils/storage-data';
import EmojiButton from '../basic/EmojiButton.vue';
import PopupSection from '../containers/PopupSection.vue';

const {
  list,
  copyAsImage = false,
} = defineProps<{
  list: Array<IStorageHistoryItem>;
  copyAsImage?: boolean;
}>();

async function handleClick(item: IStorageHistoryItem) {
  try {
    await copy({
      value: item.link,
      asImage: copyAsImage,
    })
  } catch (error) {
    console.error('Copy failed:', error)
  }
}
</script>

<template>
  <PopupSection class="historyListComponent" title="Recently copied emojis" isIndicatable :indicatorValue="list">
    <div class="content">
      <EmojiButton v-for="thisItem in list" :key="thisItem.link" :imageUrl="thisItem.link"
        @click="handleClick(thisItem)" />
    </div>
  </PopupSection>
</template>

<style scoped>
.content {
  display: grid;
  grid-template-columns: repeat(10, 1fr);
  gap: 7px;
}
</style>

// src/pages/popup/history-list.svelte
<script>
  import { CopyModesEnum } from '../../interfaces';
  import EmojiButton from '../../components/emoji-button.svelte';
  import { copy } from '../../helpers';

  export let items;
  export let mode = CopyModesEnum.link;

  $: reversedList = [...items].reverse();

  function onClick({
    item,
  }) {
    copy({
      value: item.link,
      asImage: mode === CopyModesEnum.image,
    }).catch(
      (error) => console.error(`Ошибка при копировании в буфер обмена: ${error}`),
    )
  }
</script>

<div>
  <h2>Recently copied emojis</h2>

  {#if reversedList.length}
    <div class="list">
      {#each reversedList as thisItem (thisItem.link)}
        <EmojiButton
          url={thisItem.link}
          on:click={() => onClick({
            item: thisItem,
          })}
        />
      {/each}
    </div>
  {:else}
    <p>history is empty</p>
  {/if}
</div>

<style lang="scss">
  .list {
    display: grid;
    grid-template-columns: repeat(10, 1fr);
    gap: 7px;
  }
</style>
